services:
  backend:
    # build:
    #   context: .
    #   dockerfile: dev/backend.Dockerfile
    image: tsmadalina10/parla-backend:latest
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    # build:
    #   context: ./dev/parla_ui
    #   dockerfile: Dockerfile
    image: tsmadalina10/parla-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
