services:
  backend:
    build:
      context: .
      dockerfile: dev/backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./dev/parla_ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
